version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beagle_backend
    restart: always
    volumes:
      - .:/beagle
    ports:
      - "8085:8080"
